// This code was autogenerated with dbus-codegen-rust
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait DeviceHsr {
    fn port1(&self) -> Result<dbus::Path<'static>, dbus::Error>;
    fn port2(&self) -> Result<dbus::Path<'static>, dbus::Error>;
    fn supervision_address(&self) -> Result<String, dbus::Error>;
    fn multicast_spec(&self) -> Result<u8, dbus::Error>;
    fn prp(&self) -> Result<bool, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> DeviceHsr for blocking::Proxy<'a, C> {

    fn port1(&self) -> Result<dbus::Path<'static>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.NetworkManager.Device.Hsr", "Port1")
    }

    fn port2(&self) -> Result<dbus::Path<'static>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.NetworkManager.Device.Hsr", "Port2")
    }

    fn supervision_address(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.NetworkManager.Device.Hsr", "SupervisionAddress")
    }

    fn multicast_spec(&self) -> Result<u8, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.NetworkManager.Device.Hsr", "MulticastSpec")
    }

    fn prp(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.freedesktop.NetworkManager.Device.Hsr", "Prp")
    }
}
